insert into public.markets (
  slug,
  title,
  competition,
  stage,
  home_name,
  home_code,
  away_name,
  away_code,
  kickoff_at,
  trading_end_at,
  status,
  provider,
  provider_event_id,
  oracle_home_probability_ppm,
  oracle_away_probability_ppm,
  oracle_source_at,
  oracle_received_at
)
values
  (
    'france-vs-england-third-place',
    'France vs England',
    'World Football Championship 2026',
    'Third-place play-off',
    'France',
    'FRA',
    'England',
    'ENG',
    '2026-07-18 21:00:00+00',
    '2026-07-19 00:00:00+00',
    'pre_match_open',
    'replay',
    'replay-fra-eng-2026',
    500000,
    500000,
    now(),
    now()
  ),
  (
    'argentina-vs-spain-final',
    'Argentina vs Spain',
    'World Football Championship 2026',
    'Final',
    'Argentina',
    'ARG',
    'Spain',
    'ESP',
    '2026-07-19 19:00:00+00',
    '2026-07-19 22:00:00+00',
    'pre_match_open',
    'replay',
    'replay-arg-esp-2026',
    500000,
    500000,
    now(),
    now()
  )
on conflict (slug) do update set
  title = excluded.title,
  competition = excluded.competition,
  stage = excluded.stage,
  home_name = excluded.home_name,
  home_code = excluded.home_code,
  away_name = excluded.away_name,
  away_code = excluded.away_code,
  kickoff_at = excluded.kickoff_at,
  trading_end_at = excluded.trading_end_at,
  updated_at = now();
