insert into public.markets (
  slug,
  title,
  competition,
  stage,
  home_name,
  home_code,
  away_name,
  away_code,
  kickoff_at,
  trading_end_at,
  status,
  provider,
  provider_event_id,
  oracle_home_probability_ppm,
  oracle_away_probability_ppm,
  oracle_source_at,
  oracle_received_at
)
values
  (
    'france-vs-england-third-place',
    'France vs England',
    'World Football Championship 2026',
    'Third-place play-off',
    'France',
    'FRA',
    'England',
    'ENG',
    '2026-07-18 21:00:00+00',
    '2026-07-19 00:00:00+00',
    'pre_match_open',
    'kalshi-fifa',
    '{"kalshi":{"homeTicker":"KXWCADVANCE-26JUL18FRAENG-FRA","awayTicker":"KXWCADVANCE-26JUL18FRAENG-ENG"},"fifa":{"competitionId":"17","seasonId":"285023","stageId":"289291","matchId":"400021542"}}',
    635000,
    365000,
    now(),
    now()
  ),
  (
    'argentina-vs-spain-final',
    'Argentina vs Spain',
    'World Football Championship 2026',
    'Final',
    'Argentina',
    'ARG',
    'Spain',
    'ESP',
    '2026-07-19 19:00:00+00',
    '2026-07-19 22:00:00+00',
    'pre_match_open',
    'kalshi-fifa',
    '{"kalshi":{"homeTicker":"KXMENWORLDCUP-26-AR","awayTicker":"KXMENWORLDCUP-26-ES"},"fifa":{"competitionId":"17","seasonId":"285023","stageId":"289292","matchId":"400021543"}}',
    413793,
    586207,
    now(),
    now()
  )
on conflict (slug) do update set
  title = excluded.title,
  competition = excluded.competition,
  stage = excluded.stage,
  home_name = excluded.home_name,
  home_code = excluded.home_code,
  away_name = excluded.away_name,
  away_code = excluded.away_code,
  kickoff_at = excluded.kickoff_at,
  trading_end_at = excluded.trading_end_at,
  provider = excluded.provider,
  provider_event_id = excluded.provider_event_id,
  oracle_home_probability_ppm = excluded.oracle_home_probability_ppm,
  oracle_away_probability_ppm = excluded.oracle_away_probability_ppm,
  updated_at = now();
