create extension if not exists pgcrypto;

create type public.market_status as enum (
  'scheduled',
  'pre_match_open',
  'live_open',
  'suspended',
  'ended',
  'settled',
  'voided'
);

create type public.market_side as enum ('home', 'away');
create type public.trade_action as enum ('buy', 'sell');
create type public.feed_status as enum ('healthy', 'stale', 'suspended', 'offline');
create type public.settlement_kind as enum ('result', 'void');
create type public.ledger_kind as enum (
  'initial_grant',
  'trade_buy',
  'trade_sell',
  'settlement',
  'void_redemption',
  'admin_adjustment',
  'reversal'
);

create table public.event_users (
  id uuid primary key default gen_random_uuid(),
  uid text not null unique check (uid ~ '^[0-9]{8}$'),
  balance_micro bigint not null default 10000000000 check (balance_micro >= 0),
  initial_points_micro bigint not null default 10000000000 check (initial_points_micro > 0),
  status text not null default 'active' check (status in ('active', 'suspended')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.uid_sessions (
  token_hash text primary key,
  user_id uuid not null references public.event_users(id) on delete cascade,
  user_agent text,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  expires_at timestamptz not null,
  check (expires_at > created_at)
);

create index uid_sessions_user_id_idx on public.uid_sessions(user_id);
create index uid_sessions_expires_at_idx on public.uid_sessions(expires_at);

create table public.markets (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique check (slug ~ '^[a-z0-9-]+$'),
  title text not null,
  competition text not null,
  stage text not null,
  home_name text not null,
  home_code text not null check (char_length(home_code) between 2 and 4),
  away_name text not null,
  away_code text not null check (char_length(away_code) between 2 and 4),
  kickoff_at timestamptz not null,
  trading_end_at timestamptz not null,
  status public.market_status not null default 'scheduled',
  outcome public.market_side,
  provider text not null default 'replay',
  provider_event_id text,
  oracle_home_probability_ppm integer not null default 500000
    check (oracle_home_probability_ppm between 0 and 1000000),
  oracle_away_probability_ppm integer not null default 500000
    check (oracle_away_probability_ppm between 0 and 1000000),
  oracle_version bigint not null default 1 check (oracle_version > 0),
  vmm_version bigint not null default 1 check (vmm_version > 0),
  oracle_source_at timestamptz,
  oracle_received_at timestamptz,
  feed_status public.feed_status not null default 'healthy',
  suspension_reason text,
  suspended_at timestamptz,
  suspended_oracle_version bigint,
  home_inventory_microshares bigint not null default 0,
  away_inventory_microshares bigint not null default 0,
  liquidity_b_microshares bigint not null default 100000000000
    check (liquidity_b_microshares > 0),
  spread_bps integer not null default 100 check (spread_bps between 0 and 1000),
  min_order_micro bigint not null default 10000000 check (min_order_micro > 0),
  max_order_micro bigint not null default 2000000000 check (max_order_micro > min_order_micro),
  max_user_exposure_micro bigint not null default 5000000000
    check (max_user_exposure_micro >= max_order_micro),
  home_score smallint not null default 0 check (home_score >= 0),
  away_score smallint not null default 0 check (away_score >= 0),
  match_minute smallint check (match_minute is null or match_minute between 0 and 150),
  match_period text,
  latest_event text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  settled_at timestamptz,
  check (trading_end_at > kickoff_at),
  check (oracle_home_probability_ppm + oracle_away_probability_ppm = 1000000),
  check ((status not in ('settled', 'voided')) or settled_at is not null),
  check ((status <> 'settled') or outcome is not null)
);

create index markets_status_kickoff_idx on public.markets(status, kickoff_at);
create index markets_provider_event_idx on public.markets(provider, provider_event_id);

create table public.odds_snapshots (
  id bigint generated by default as identity primary key,
  market_id uuid not null references public.markets(id) on delete cascade,
  provider text not null,
  provider_event_id text,
  home_decimal_odds numeric(12, 6),
  away_decimal_odds numeric(12, 6),
  home_probability_ppm integer not null check (home_probability_ppm between 0 and 1000000),
  away_probability_ppm integer not null check (away_probability_ppm between 0 and 1000000),
  oracle_version bigint not null,
  source_at timestamptz not null,
  received_at timestamptz not null default now(),
  raw_payload jsonb,
  check (home_probability_ppm + away_probability_ppm = 1000000)
);

create index odds_snapshots_market_time_idx
  on public.odds_snapshots(market_id, source_at desc);

create table public.positions (
  user_id uuid not null references public.event_users(id) on delete cascade,
  market_id uuid not null references public.markets(id) on delete cascade,
  home_shares_micro bigint not null default 0 check (home_shares_micro >= 0),
  away_shares_micro bigint not null default 0 check (away_shares_micro >= 0),
  home_cost_micro bigint not null default 0 check (home_cost_micro >= 0),
  away_cost_micro bigint not null default 0 check (away_cost_micro >= 0),
  gross_bought_micro bigint not null default 0 check (gross_bought_micro >= 0),
  net_cost_micro bigint not null default 0,
  realized_pnl_micro bigint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, market_id)
);

create index positions_market_idx on public.positions(market_id);

create table public.trades (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.event_users(id) on delete restrict,
  market_id uuid not null references public.markets(id) on delete restrict,
  side public.market_side not null,
  action public.trade_action not null,
  cash_delta_micro bigint not null,
  shares_micro bigint not null check (shares_micro > 0),
  average_price_ppm integer not null check (average_price_ppm between 1 and 999999),
  oracle_probability_ppm integer not null check (oracle_probability_ppm between 0 and 1000000),
  oracle_version bigint not null,
  vmm_version bigint not null,
  quote_id uuid not null,
  idempotency_key text not null check (char_length(idempotency_key) between 8 and 100),
  created_at timestamptz not null default now(),
  unique (user_id, idempotency_key),
  check ((action = 'buy' and cash_delta_micro < 0) or (action = 'sell' and cash_delta_micro > 0))
);

create index trades_market_time_idx on public.trades(market_id, created_at desc);
create index trades_user_time_idx on public.trades(user_id, created_at desc);

create table public.ledger_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.event_users(id) on delete restrict,
  market_id uuid references public.markets(id) on delete restrict,
  trade_id uuid references public.trades(id) on delete restrict,
  kind public.ledger_kind not null,
  amount_micro bigint not null,
  balance_after_micro bigint not null check (balance_after_micro >= 0),
  note text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create unique index ledger_initial_grant_once_idx
  on public.ledger_entries(user_id)
  where kind = 'initial_grant';
create index ledger_user_time_idx on public.ledger_entries(user_id, created_at desc);

create table public.settlements (
  id uuid primary key default gen_random_uuid(),
  market_id uuid not null unique references public.markets(id) on delete restrict,
  kind public.settlement_kind not null,
  outcome public.market_side,
  result_source text not null,
  result_reference text,
  settled_by text not null,
  total_payout_micro bigint not null default 0 check (total_payout_micro >= 0),
  affected_users integer not null default 0 check (affected_users >= 0),
  created_at timestamptz not null default now(),
  check ((kind = 'result' and outcome is not null) or (kind = 'void' and outcome is null))
);

create table public.leaderboard_entries (
  user_id uuid primary key references public.event_users(id) on delete cascade,
  masked_uid text not null,
  balance_micro bigint not null default 0,
  position_value_micro bigint not null default 0,
  equity_micro bigint not null default 0,
  pnl_micro bigint not null default 0,
  correct_predictions integer not null default 0,
  settled_predictions integer not null default 0,
  updated_at timestamptz not null default now()
);

create index leaderboard_rank_idx
  on public.leaderboard_entries(
    equity_micro desc,
    pnl_micro desc,
    correct_predictions desc,
    updated_at asc
  );

create table public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  market_id uuid references public.markets(id) on delete restrict,
  actor text not null,
  action text not null,
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger event_users_set_updated_at
before update on public.event_users
for each row execute function public.set_updated_at();

create trigger markets_set_updated_at
before update on public.markets
for each row execute function public.set_updated_at();

create trigger positions_set_updated_at
before update on public.positions
for each row execute function public.set_updated_at();

create or replace function public.mask_uid(value text)
returns text
language sql
immutable
strict
as $$
  select left(value, 2) || '****' || right(value, 2);
$$;

alter table public.event_users enable row level security;
alter table public.uid_sessions enable row level security;
alter table public.markets enable row level security;
alter table public.odds_snapshots enable row level security;
alter table public.positions enable row level security;
alter table public.trades enable row level security;
alter table public.ledger_entries enable row level security;
alter table public.settlements enable row level security;
alter table public.leaderboard_entries enable row level security;
alter table public.admin_audit_logs enable row level security;

create policy markets_public_read
on public.markets for select
to anon, authenticated
using (true);

create policy leaderboard_public_read
on public.leaderboard_entries for select
to anon, authenticated
using (true);

grant usage on schema public to anon, authenticated, service_role;
grant select on public.markets, public.leaderboard_entries to anon, authenticated;
grant all privileges on all tables in schema public to service_role;
grant usage, select on all sequences in schema public to service_role;

alter default privileges in schema public
grant all privileges on tables to service_role;
alter default privileges in schema public
grant usage, select on sequences to service_role;

revoke all on public.event_users, public.uid_sessions, public.odds_snapshots,
  public.positions, public.trades, public.ledger_entries, public.settlements,
  public.admin_audit_logs from anon, authenticated;

do $$
begin
  alter publication supabase_realtime add table public.markets;
exception
  when duplicate_object then null;
end;
$$;

do $$
begin
  alter publication supabase_realtime add table public.leaderboard_entries;
exception
  when duplicate_object then null;
end;
$$;
